apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingcart-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shoppingcart-api
  template:
    metadata:
      labels:
        app: shoppingcart-api
    spec:
      containers:
      - name: api
        image: ${DOCKER_REGISTRY}/shoppingcart-api:${IMAGE_TAG}
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: shoppingcart-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: shoppingcart-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: shoppingcart-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shoppingcart-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: shoppingcart-config
              key: DB_NAME
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5 