# 使用 3.8 版的設定檔，通常新版本會有新的功能，並支援新的設定參數
version: "3.8"

# 定義 service 的區塊，一個 service 設定可以用來啟動多個 container
services:
  shoppingcar-service:
    container_name: shoppingcar-service
    image: passon/shoppingcar-service
    ports:
      - 0.0.0.0:3333:3333
    volumes:
      - .env:/app/.env

