name: "Deployment"

description: "Deploy newest code to the machine."

inputs:
  folder-name:
    description: 'Project folder name'
    required: true
  module-name:
    description: '模組名稱'
    required: true
  secrets-env:
    description: 'service env'
    required: true
  ssh-key:
    description: 'Ssh key for login the target machine'
    required: true
  host-name:
    description: 'Host domain or ip'
    required: true
  branch-name:
    description: 'The branch you want to checkout with'
    required: true
runs:
  using: "composite"
  steps:
    - name: Pulling newest code and restart docker app
      uses: fifsky/ssh-action@master
      with:
        command: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd ./${{ inputs.folder-name }}
          echo "${{ inputs.secrets-env }}" > .env
          docker-compose down --rmi all || echo "stop docker compose service"
          docker-compose up -d
        host: ${{ inputs.host-name }}
        user: root
        key: ${{ inputs.ssh-key }}
