name: "Deployment"

description: "Deploy newest code to the machine."

inputs:
  ssh-key:
    description: 'Ssh key for login the target machine'
    required: true
  host-name:
    description: 'Host domain or ip'
    required: true
runs:
  using: "composite"
  steps:
    - name: Pulling newest code and restart docker app
      uses: fifsky/ssh-action@master
      with:
        command: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd /opt/services/shoppingcar-services
          yarn install
          pm2 delete ecosystem.config.js|| echo "deleted process"
          pm2 start ecosystem.config.js
        host: ${{ inputs.host-name }}
        user: root
        key: ${{ inputs.ssh-key }}
