name: 部署購物車服務API

on:
  push:
    branches:
      - develop
    paths:
      - 'backend/**'
      - 'deploy/shoppingcar-service-api/**'
      - '.github/workflows/deploy-shoppingcar-api-docker.yaml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: mac-mini-build
    steps:
      - name: 檢出代碼
        uses: actions/checkout@v3

      - name: 設置QEMU
        uses: docker/setup-qemu-action@v2

      - name: 設置Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 登錄到DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: 構建並推送Docker鏡像
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deploy/shoppingcar-service-api/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: passon/shoppingcar-service-api:lastest

      - name: 部署到遠程服務器
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_BACKEND_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /opt/services/apps/shoppingcar-service/api-service/
            docker-compose pull
            docker-compose down
            docker-compose up -d
            docker image prune -f 